// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LOGIN_SC_IN.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "LOGIN_SC_IN.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Login {

namespace {

const ::google::protobuf::Descriptor* Login_SC_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Login_SC_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_LOGIN_5fSC_5fIN_2eproto() {
  protobuf_AddDesc_LOGIN_5fSC_5fIN_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "LOGIN_SC_IN.proto");
  GOOGLE_CHECK(file != NULL);
  Login_SC_descriptor_ = file->message_type(0);
  static const int Login_SC_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Login_SC, rtcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Login_SC, uid_),
  };
  Login_SC_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Login_SC_descriptor_,
      Login_SC::default_instance_,
      Login_SC_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Login_SC, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Login_SC, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Login_SC));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_LOGIN_5fSC_5fIN_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Login_SC_descriptor_, &Login_SC::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_LOGIN_5fSC_5fIN_2eproto() {
  delete Login_SC::default_instance_;
  delete Login_SC_reflection_;
}

void protobuf_AddDesc_LOGIN_5fSC_5fIN_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021LOGIN_SC_IN.proto\022\005Login\"\'\n\010Login_SC\022\016"
    "\n\006rtcode\030\001 \002(\t\022\013\n\003uid\030\002 \002(\005", 67);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "LOGIN_SC_IN.proto", &protobuf_RegisterTypes);
  Login_SC::default_instance_ = new Login_SC();
  Login_SC::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_LOGIN_5fSC_5fIN_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_LOGIN_5fSC_5fIN_2eproto {
  StaticDescriptorInitializer_LOGIN_5fSC_5fIN_2eproto() {
    protobuf_AddDesc_LOGIN_5fSC_5fIN_2eproto();
  }
} static_descriptor_initializer_LOGIN_5fSC_5fIN_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Login_SC::kRtcodeFieldNumber;
const int Login_SC::kUidFieldNumber;
#endif  // !_MSC_VER

Login_SC::Login_SC()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Login_SC::InitAsDefaultInstance() {
}

Login_SC::Login_SC(const Login_SC& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Login_SC::SharedCtor() {
  _cached_size_ = 0;
  rtcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  uid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Login_SC::~Login_SC() {
  SharedDtor();
}

void Login_SC::SharedDtor() {
  if (rtcode_ != &::google::protobuf::internal::kEmptyString) {
    delete rtcode_;
  }
  if (this != default_instance_) {
  }
}

void Login_SC::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Login_SC::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Login_SC_descriptor_;
}

const Login_SC& Login_SC::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_LOGIN_5fSC_5fIN_2eproto();
  return *default_instance_;
}

Login_SC* Login_SC::default_instance_ = NULL;

Login_SC* Login_SC::New() const {
  return new Login_SC;
}

void Login_SC::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_rtcode()) {
      if (rtcode_ != &::google::protobuf::internal::kEmptyString) {
        rtcode_->clear();
      }
    }
    uid_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Login_SC::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string rtcode = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rtcode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->rtcode().data(), this->rtcode().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_uid;
        break;
      }

      // required int32 uid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Login_SC::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string rtcode = 1;
  if (has_rtcode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->rtcode().data(), this->rtcode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->rtcode(), output);
  }

  // required int32 uid = 2;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->uid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Login_SC::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string rtcode = 1;
  if (has_rtcode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->rtcode().data(), this->rtcode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->rtcode(), target);
  }

  // required int32 uid = 2;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->uid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Login_SC::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string rtcode = 1;
    if (has_rtcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->rtcode());
    }

    // required int32 uid = 2;
    if (has_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->uid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Login_SC::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Login_SC* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Login_SC*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Login_SC::MergeFrom(const Login_SC& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_rtcode()) {
      set_rtcode(from.rtcode());
    }
    if (from.has_uid()) {
      set_uid(from.uid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Login_SC::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Login_SC::CopyFrom(const Login_SC& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Login_SC::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Login_SC::Swap(Login_SC* other) {
  if (other != this) {
    std::swap(rtcode_, other->rtcode_);
    std::swap(uid_, other->uid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Login_SC::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Login_SC_descriptor_;
  metadata.reflection = Login_SC_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Login

// @@protoc_insertion_point(global_scope)
